[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { path = "../rocket" }
db = { path = "../db" }
utils = { path = "../utils" }
serde = { path = "../serde" }
jsonwebtoken = { version = "9.3.0" }
cookie = { version = "0.18.1" }
bcrypt = "0.15.1"